environment.name=PROD

#management.tracing.sampling.probability=0.1
#management.otlp.metrics.export.url=http://localhost:4318/v1/metrics
#management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces
#management.opentelemetry.logging.export.otlp.endpoint=http://localhost:4318/v1/logs

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

# Standard Production Logging
logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.orm.jdbc.bind=ERROR

# spring security logging
logging.level.org.springframework.security=INFO
logging.level.org.springframework.security.web.access.intercept.FilterSecurityInterceptor=WARN

# Set a standard ISO format with time zone support
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss.SSSZ

# Disable pretty printing to save bandwidth
spring.jackson.serialization.indent-output=false

# Recommended: Don't send null fields to save even more space
spring.jackson.default-property-inclusion=non_null

# 1. Use standard human-readable format
# Remove or comment out the ECS lines

# 2. Log to a file so you can SSH in and read them
logging.file.name=logs/app.log

#server.error.include-message=never
#server.error.include-stacktrace=never
#server.error.include-binding-errors=never

# 3. CRITICAL: Set up Rotation (Spring Boot does this automatically)
# This prevents the file from growing to 50GB and crashing your server
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.total-size-cap=1GB
logging.logback.rollingpolicy.max-history=30