name: Native Build
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    name: Build Native Image
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/graalvm/native-image-community:21
      options: --entrypoint ""

    steps:
      - uses: actions/checkout@v4

      - name: Install Maven
        run: |
          curl -fsSL https://archive.apache.org/dist/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz | tar -xz -C /opt
          ln -s /opt/apache-maven-3.9.6/bin/mvn /usr/local/bin/mvn

      - name: Build & compile native image
        run: mvn clean package native:compile -Pnative -Dmaven.test.skip=true

      - name: List target
        run: ls -la target/

      - name: Upload native image artifact
        uses: actions/upload-artifact@v4
        with:
          name: native-image
          path: target/
